### ISSUE TITLE
Mac M1 (arm) support 

### ISSUE THREAD

**Issue by bourbonfgiles** [davidsbond/terraform-provider-tailscale#22]
Currently the provider does not support M1 based Macs.

**Comment by davidsbond** [comment]
Hey @bourbonfgiles, it _should_ be easy for me to add this to the goreleaser config. I'll get this included and do a new release shortly

**Comment by davidsbond** [comment]
Here you go, the `0.1.1` release provides a `darwin/arm64` binary now:

https://github.com/davidsbond/terraform-provider-tailscale/releases/download/v0.1.1/terraform-provider-tailscale_0.1.1_darwin_arm64.zip

**Comment by davidsbond** [comment]
Just note there was a breaking change from a previous commit included in the release as well. In the `provider` block the word `tailnet` is used instead of `domain`.

Happy terraforming!

**Comment by bourbonfgiles** [comment]
Noted, thanks! :)
