### ISSUE TITLE
tailscale_device_subnet_routes: Failed to fetch dns nameservers

### ISSUE THREAD

**Issue by feraudet** [davidsbond/terraform-provider-tailscale#31]
**Describe the bug**
When refreshing state I get `Error: Failed to fetch dns nameservers`

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Machine with `--accept-dns=false`
2. Add subnet routes using  `tailscale_device_subnet_routes`
3. `terraform plan`

**Expected behaviour**
A refreshed state

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Terraform v0.15.5
 - Provider Version v0.1.3

**Additional context**
Complete error : 
> │ Error: Failed to fetch dns nameservers
> │
> │   with tailscale_device_subnet_routes.nodes[0],
> │   on main.tf line 26, in resource "tailscale_device_subnet_routes" "nodes":
> │   26: resource "tailscale_device_subnet_routes" "nodes" {
> │
> │ invalid character 'u' looking for beginning of value

**Comment by davidsbond** [comment]
Hey @feraudet, thanks for the bug report. I'll try to reproduce and see how to implement a fix. For now it looks like the API is returning an error that isn't in JSON format, so it's not telling you what the problem is. 

I'll have a dig and see what I find

**Comment by davidsbond** [comment]
Found the problem, looks like there was a whitespace in the URI path, which is a problem that happened on another endpoint also. I need to invest some time into adding some better integration testing for the tailscale client.

Otherwise, I'll merge the fix in and release a new version shortly.

**Comment by davidsbond** [comment]
Give it 5 minutes and you should be able to grab v0.1.4 which should hopefully fix the problem. Let me know if there are any further problems :)

**Comment by feraudet** [comment]
It work perfectly now, thank you !
