### ISSUE TITLE
Permanent diff in ACL resources

### ISSUE THREAD

**Issue by johnae** [davidsbond/terraform-provider-tailscale#62]
**Describe the bug**
I get a permadiff when running terraform plan/apply.

Since I'm fairly certain WHY I get a permadiff, I will just link to the issue I posted in the tailscale github org. (i.e I don't believe it's the terraform provider's fault but it's clearly a problem that is very visible here):

https://github.com/tailscale/tailscale/issues/3723

**Comment by davidsbond** [comment]
Hey @johnae, thanks for raising this. Definitely appears to be a problem in the Tailscale API. I'll keep this issue open just in case others come to this repository with the same problem.

This provider always requests ACL data from the Tailscale API in JSON, but supports providing ACL's in hujson, which causes the difference to appear in the terraform provider.

**Comment by johnae** [comment]
The issue actually seems to be that in the json result the groups are always expanded while in hujson they're not but afaik that has nothing to do with hujson right? I assume, in json, I can specify the tag owner as being a group or am I wrong here?

**Comment by davidsbond** [comment]
That should have nothing to do with hujson specifically as far as I know, I think it's more likely their API implementation has two separate endpoints for the different content types. Those two endpoint's behaviour has likely diverged over time and is causing the difference. That's just conjecture from me though.

**Comment by dsnet** [comment]
There was a bug where the ACL returned is semantically different depending on whether JSON or HuJSON was requested. This will be fixed shortly.

That said, I'm not too familiar with Terraform and I'm trying to understand the permanent diff issue. How are the ACLs being compared? Is it checking that the ACLs are byte-for-byte identical or is doing a more semantic diff?

For example, byte-for-byte equivalence would be something like:
```go
return bytes.Equal(aclBefore, aclAfter)
```
while semantic equivalence would be something like:
```go
var before, after any
json.Unmarshal(beforeAcl, &before)
json.Unmarshal(afterAcl, &after)
return reflect.DeepEqual(before, after)
```

The reason I ask is because after fixing https://github.com/tailscale/tailscale/issues/3723, we plan on [automatically formatting all HuJSON ACLs](https://pkg.go.dev/github.com/tailscale/hujson#Value.Format) upon saving. The formatting only changes whitespace, so it will break logic that depends on byte-for-byte equivalence, but will be okay for those checking for semantic equivalence.

**Comment by davidsbond** [comment]
Hey @dsnet, thanks for the info. 

Each resource in terraform is described by a schema, which is fairly simple list of fields that can be of a particular type (strings, numbers, maps, objects etc...). When terraform checks if a resource needs changing, it uses the plugin to request the upstream state (i.e an HTTP GET request to /acl), using the schema, an object is created using the upstream state, which is then compared with the object in the terraform state. 

The ACL code for this provider is slightly different. In this provider we marshal into and out of structs that represent an ACL. Then use a special feature of the SDK to supress diffs in the raw bytes of the ACL by checking the value of the go structs match:

```go
func suppressACLDiff(_, old, new string, _ *schema.ResourceData) bool {
	var oldACL tailscale.ACL
	var newACL tailscale.ACL

	if err := hujson.Unmarshal([]byte(old), &oldACL); err != nil {
		return false
	}

	if err := hujson.Unmarshal([]byte(new), &newACL); err != nil {
		return false
	}

	return cmp.Equal(oldACL, newACL)
}
```

^ This is effectively it. So changes in byte content shouldn't matter, as we don't perform byte for byte comparisons.

All the code for ACL handling is here if you would like to look:

https://github.com/davidsbond/terraform-provider-tailscale/blob/master/tailscale/resource_acl.go

**Comment by davidsbond** [comment]
Thanks for contributing those changes! Does the upstream issue being closed mean that the bug has been resolved?

**Comment by dsnet** [comment]
The code fix has been submitted, but has not yet been deployed to production. That will probably happen sometime in the next day or so. I can ping this issue when it occurs.

**Comment by davidsbond** [comment]
Awesome, thanks again @dsnet.

**Comment by dsnet** [comment]
Fix deployed. Asking for `application/json` should be identical to `application/hujson` except all HuJSON-specific artifacts are replaced with spaces.

**Comment by davidsbond** [comment]
@johnae please upgrade to the latest version of the provider and check if you still see the same issue with the permanent diff.

**Comment by davidsbond** [comment]
Going to close this for now as I assume this issue is resolved. Can reopen if there are any further issues.
