### ISSUE TITLE
FR: add support for managing tags

### ISSUE THREAD

**Issue by rsyring** [davidsbond/terraform-provider-tailscale#67]
**Is your feature request related to a problem? Please describe.**

Unable to manage device tags.

**Describe the solution you'd like**

I'd like to be able to manage a device's ACL tags using Terraform.  It would appear that the API supports this: https://github.com/tailscale/tailscale/blob/main/api.md#device-tags-post

**Comment by davidsbond** [comment]
Hello @rsyring, thanks for the issues you've raised. I am currently driving a Soviet era Lada from Portugal to the UK and will be able to take a proper look at your feature requests next week. 

Pull requests are welcome if you're feeling up to it! The Tailscale client package is in a separate repository of mine so functionality will need to be added there first.

**Comment by davidsbond** [comment]
This seems like an appropriate feature to me, perhaps a `tailscale_device_tags` resource like this:

```terraform
resource "tailscale_device_tags" "example_tags" {
  device_id = data.tailscale_device.my_device.id
  tags = {
    "hello": "world"
  }
}
```

What do you think?
