### ISSUE TITLE
Unable to add tests to ACL

### ISSUE THREAD

**Issue by mikevischer** [davidsbond/terraform-provider-tailscale#89]
I have been having issues implementing [ACL tests](https://tailscale.com/kb/1018/acls/#tests) with the Terraform provider.   Once I add the tests section and try to `terraform apply` I receive the following error.

```
│ Error: Failed to set ACL
│
│   with tailscale_acl.cio_acl,
│   on main.tf line 1, in resource "tailscale_acl" "cio_acl":
│    1: resource "tailscale_acl" "cio_acl" {
│
│ test(s) failed (400)
```

I am able to apply the same JSON file through the Tailscale API, so this issue only occurs with the Terraform provider.

**Comment by davidsbond** [comment]
Hi @mikevischer, thanks for raising this issue. If you get no issues when going directly via the API it sounds like a bug in the provider. 

Could you please provide some info as to which version of the provider you're using? And if possible, provide a small example to reproduce the issue?

**Comment by mikevischer** [comment]
I am using version 0.7.0 of the provider.  My initial attempt was to just add a single test.

```
  "tests": [
    { "src": "group:sre", "accept": ["tag:us-production:22", "tag:eu-production:22"] }
  ],
```

Thanks!

**Comment by davidsbond** [comment]
Thanks for the info. I believe the issue is that the policy syntax has changed and the current client implementation does not support the fields you want. Namely the `src` and `dst` fields. The current client implementation has the ACL entry type as follows:

```go
type ACLEntry struct {
	Action string   `json:"action" hujson:"Action"`
	Ports  []string `json:"ports" hujson:"Ports"`
	Users  []string `json:"users" hujson:"Users"`
}
```

It appears the provider is just out of date with the syntax. So I'll need to add those new fields. Also, if you update to the latest version, you should be able to see more details on why the tests themselves failed. But I suspect it's just because the `src` field never gets sent to the API in the first place.

**Comment by davidsbond** [comment]
I will do a patch release now and hopefully your ACL should make it to the API unhindered!

**Comment by mikevischer** [comment]
That makes sense.  I was working with Tailscale support recently and they did mention syntax for tests was changing.  I went ahead and updated version 0.9.0 of the provider and the apply failed in a different way.

```
│ Error: Plugin did not respond
│
│   with tailscale_acl.cio_acl,
│   on main.tf line 1, in resource "tailscale_acl" "cio_acl":
│    1: resource "tailscale_acl" "cio_acl" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-tailscale_v0.9.0 plugin:

panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation

goroutine 55 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.DiagsToProto({0x14000096300, 0x2, 0x2})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:72 +0x2d4
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.AppendProtoDiag({0x0, 0x0, 0x0}, {0x10169fbe0, 0x1400000c1f8})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:25 +0x70
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400030c078, {0x1017854b8, 0x14000050340}, 0x14000316320)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:978 +0xe90
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400033c680, {0x101785560, 0x14000112810}, 0x140004fc1c0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x338
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x101741b40, 0x1400033c680}, {0x101785560, 0x14000112810}, 0x14000300360, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000328700, {0x101790af8, 0x140004024e0}, 0x1400000a360, 0x140003ca540, 0x101c127a0, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1282 +0xc60
google.golang.org/grpc.(*Server).handleStream(0x14000328700, {0x101790af8, 0x140004024e0}, 0x1400000a360, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1616 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400042c520, 0x14000328700, {0x101790af8, 0x140004024e0}, 0x1400000a360)
        google.golang.org/grpc@v1.43.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.43.0/server.go:919 +0x1f0

Error: The terraform-provider-tailscale_v0.9.0 plugin crashed!
```

**Comment by davidsbond** [comment]
Interesting, that looks like a different issue regarding setting the summary field in errors. I'll take a look at that now.

**Comment by davidsbond** [comment]
Okay @mikevischer! Please give v0.9.2 a try

**Comment by mikevischer** [comment]
I just tried with v0.9.2 and now receive this

```
│ Error: Invalid ACL
│
│   with tailscale_acl.cio_acl,
│   on main.tf line 2, in resource "tailscale_acl" "cio_acl":
│    2:   acl = file("cio_acl.json")
│
│ json: cannot unmarshal string into Go struct field ACLTest.tests.src of
│ type []string
```

**Comment by davidsbond** [comment]
Thanks for all the testing for me! I don't have a super appropriate testing environment for checking ACLs etc. It's late now where I am but I will correct this tomorrow. I misconstrued the types they use in the test portion of the ACL.

**Comment by mikevischer** [comment]
Sounds good.  Thanks for helping out so quickly!

**Comment by mikevischer** [comment]
Hi @davidsbond.  Using v.0.9.3 gives me a new error.

```
│ Error: Failed to set ACL
│
│   with tailscale_acl.cio_acl,
│   on main.tf line 1, in resource "tailscale_acl" "cio_acl":
│    1: resource "tailscale_acl" "cio_acl" {
│
│ json: unknown field "dst" (400)
```

I looks like the current ACL file syntax for tests only uses the keys `src`, `accept`, and `deny`.
https://tailscale.com/kb/1018/acls/#tests

Thanks again for all of your help here.

**Comment by davidsbond** [comment]
Thanks, will raise a fix. Apologies for using you as the guinea pig for these changes! Hopefully this is the last one.

**Comment by davidsbond** [comment]
Going to keep this open until we're sure your stuff works :P

**Comment by davidsbond** [comment]
@mikevischer v0.9.4 should be available in the terraform registry shortly. Please give it a go and hopefully that's the last thing to get ACLs up-to-date with the latest syntax.

**Comment by davidsbond** [comment]
Hey no worries, sorry for having to go through so many versions to get it sorted! Hopefully some time in the future I can put together a reasonable enough test environment for these sort of things. Right now I only have my homelab and I don't want to accidentally break things!
